# Generated by Django 6.0.1 on 2026-04-04 06:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_intterest_percentage_alter_intterest_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='intterest',
            name='interest_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='intterest',
            constraint=models.UniqueConstraint(fields=('student', 'interest_name'), name='unique_student_interest_name'),
        ),
    ]
