# Generated by Django 6.0.1 on 2026-04-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_intterest_interest_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='recommended_courses/')),
                ('course_type', models.CharField(choices=[('toefl_ielts', 'TOEFL / IELTS'), ('professional', 'Professional'), ('immigration', 'Immigration')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['course_type', '-created_at'],
            },
        ),
    ]
