# Generated by Django 6.0.1 on 2026-04-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_recommendedcourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendedcourse',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='recommendedcourse',
            name='course_type',
        ),
        migrations.AddField(
            model_name='recommendedcourse',
            name='course_types',
            field=models.ManyToManyField(blank=True, limit_choices_to={'student__isnull': True}, related_name='recommended_courses', to='students.intterest', verbose_name='Course type'),
        ),
    ]
