# Generated by Django 6.0.1 on 2026-04-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_recommendedcourse_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedcourse',
            name='course_types',
            field=models.ManyToManyField(blank=True, related_name='recommended_courses', to='students.intterest', verbose_name='Course type'),
        ),
    ]
