# Generated by Django 6.0.1 on 2026-04-04 06:48

from decimal import Decimal, ROUND_HALF_UP

from django.db import migrations, models
from django.db.models import Count


def rebuild_interest_summaries(apps, schema_editor):
    Intterest = apps.get_model("students", "Intterest")
    InterestSummary = apps.get_model("students", "InterestSummary")

    selections = Intterest.objects.exclude(student__isnull=True)
    total_students = selections.values("student_id").distinct().count()

    if total_students == 0:
        return

    for item in (
        selections.values("interest_name")
        .annotate(student_count=Count("student_id", distinct=True))
        .order_by("interest_name")
    ):
        percentage = (
            Decimal(item["student_count"]) * Decimal("100.00") / Decimal(total_students)
        ).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)

        InterestSummary.objects.update_or_create(
            interest_name=item["interest_name"],
            defaults={
                "student_count": item["student_count"],
                "percentage": percentage,
            },
        )


def clear_interest_summaries(apps, schema_editor):
    InterestSummary = apps.get_model("students", "InterestSummary")
    InterestSummary.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_recommendedcourse_course_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_name', models.CharField(max_length=255, unique=True)),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Interest Summary',
                'verbose_name_plural': 'Interest Summaries',
                'ordering': ['interest_name'],
            },
        ),
        migrations.RemoveField(
            model_name='intterest',
            name='percentage',
        ),
        migrations.RunPython(rebuild_interest_summaries, clear_interest_summaries),
    ]
