# Generated by Django 6.0.1 on 2026-04-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_interestsummary_remove_intterest_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendedcourse',
            old_name='course_types',
            new_name='interest_type',
        ),
        migrations.AlterField(
            model_name='recommendedcourse',
            name='interest_type',
            field=models.ManyToManyField(
                blank=True,
                related_name='recommended_courses',
                to='students.intterest',
                verbose_name='Interest type',
            ),
        ),
    ]
