# Generated by Django 6.0.1 on 2026-04-04 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_remove_recommendedcourse_course_types_and_more'),
        ('teachers', '0004_remove_teacher_recommended_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedcourse',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_courses', to='teachers.teacher'),
        ),
    ]
