# Generated by Django 6.0.1 on 2026-04-04 08:47

from django.db import migrations, models


def copy_teacher_to_teachers(apps, schema_editor):
    RecommendedCourse = apps.get_model("students", "RecommendedCourse")

    for course in RecommendedCourse.objects.exclude(teacher__isnull=True):
        course.teachers.add(course.teacher_id)


def clear_teachers_relationship(apps, schema_editor):
    RecommendedCourse = apps.get_model("students", "RecommendedCourse")

    for course in RecommendedCourse.objects.all():
        course.teachers.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_recommendedcourse_teacher'),
        ('teachers', '0004_remove_teacher_recommended_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedcourse',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='recommended_courses', to='teachers.teacher', verbose_name='Teachers'),
        ),
        migrations.RunPython(copy_teacher_to_teachers, clear_teachers_relationship),
        migrations.RemoveField(
            model_name='recommendedcourse',
            name='teacher',
        ),
    ]
