# Generated by Django 6.0.1 on 2026-04-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_remove_recommendedcourse_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedcourse',
            name='resource_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='recommendedcourse',
            name='seat_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
