# Generated by Django 6.0.1 on 2026-04-06 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_recommendedcourse_resource_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedcourse',
            name='seat_limit',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(40)]),
        ),
    ]
