# Generated by Django 6.0.1 on 2026-04-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_recommendedcourse_seat_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedcourse',
            name='course_curriculum',
            field=models.FileField(blank=True, upload_to='course_curriculum_files/'),
        ),
        migrations.AddField(
            model_name='recommendedcourse',
            name='course_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
