# Generated by Django 6.0.1 on 2026-04-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_recommendedcourse_course_curriculum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calender_upload', models.FileField(upload_to='calender_files/')),
            ],
            options={
                'verbose_name': 'Calender',
                'verbose_name_plural': 'Calender',
                'ordering': ['-id'],
            },
        ),
    ]
