# Generated by Django 6.0.1 on 2026-04-07 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_calender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calender',
        ),
    ]
