# Generated by Django 6.0.1 on 2026-04-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_delete_calender'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedcourse',
            name='course_calender',
            field=models.FileField(blank=True, upload_to='course_calender_files/'),
        ),
    ]
