# Generated by Django 6.0.1 on 2026-04-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0017_recommendedcourse_course_calender"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentLocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
