# Generated by Django 6.0.1 on 2026-04-08 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_studentprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('mcq', 'MCQ'), ('true_false', 'True / False'), ('short', 'Short Answer'), ('writing', 'Writing')], max_length=20)),
                ('prompt', models.TextField()),
                ('prompt_i18n', models.JSONField(blank=True, default=dict)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='assessment_audio/')),
                ('transcript', models.TextField(blank=True)),
                ('marks', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['section', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('skill', models.CharField(choices=[('reading', 'Reading'), ('listening', 'Listening'), ('writing', 'Writing')], max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('section_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
            ],
            options={
                'ordering': ['template', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('text_i18n', models.JSONField(blank=True, default=dict)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='students.assessmentquestion')),
            ],
            options={
                'ordering': ['question', 'order', 'id'],
                'unique_together': {('question', 'order')},
            },
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='students.assessmentsection'),
        ),
        migrations.CreateModel(
            name='AssessmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.AddField(
            model_name='assessmentsection',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='students.assessmenttemplate'),
        ),
        migrations.CreateModel(
            name='StudentAssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('submitted', 'Submitted'), ('evaluated', 'Evaluated')], default='started', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('reading_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('listening_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('writing_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='students.assessmenttemplate')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='assessmentquestion',
            unique_together={('section', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='assessmentsection',
            unique_together={('template', 'skill', 'order')},
        ),
        migrations.CreateModel(
            name='AssessmentLevelBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('min_score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order', models.PositiveIntegerField(default=1)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_bands', to='students.assessmenttemplate')),
            ],
            options={
                'ordering': ['template', 'order', 'id'],
                'unique_together': {('template', 'order')},
            },
        ),
        migrations.CreateModel(
            name='StudentAssessmentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('auto_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('teacher_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='students.assessmentquestion')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_answers', to='students.assessmentoption')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='students.studentassessmentattempt')),
            ],
            options={
                'ordering': ['attempt', 'question__order', 'id'],
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
