# Generated by Django 6.0.1 on 2026-04-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_assessmentquestion_assessmentsection_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessmentlevelband',
            unique_together={('template', 'order')},
        ),
        migrations.AlterField(
            model_name='assessmentlevelband',
            name='label',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentlevelband',
            unique_together={('template', 'label'), ('template', 'order')},
        ),
    ]
