# Generated by Django 6.0.3 on 2026-04-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_alter_assessmentlevelband_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentquestion',
            name='max_listens',
            field=models.PositiveIntegerField(blank=True, default=2, help_text='Maximum number of times the audio can be played', null=True),
        ),
        migrations.AddField(
            model_name='studentassessmentanswer',
            name='listen_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times audio was played'),
        ),
        migrations.AddField(
            model_name='studentassessmentattempt',
            name='grammar_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='studentassessmentattempt',
            name='vocabulary_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentlevelband',
            name='label',
            field=models.CharField(choices=[('elementary_a1', 'Elementary (A1)'), ('pre_intermediate_a2', 'Pre-Intermediate (A2)'), ('intermediate_b1', 'Intermediate (B1)'), ('upper_intermediate_b2', 'Upper-Intermediate (B2)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='assessmentsection',
            name='skill',
            field=models.CharField(choices=[('reading', 'Reading'), ('listening', 'Listening'), ('writing', 'Writing'), ('grammar', 'Grammar'), ('vocabulary', 'Vocabulary')], max_length=20),
        ),
    ]
