# Generated by Django 6.0.3 on 2026-04-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_assessmentquestion_max_listens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttemplate',
            name='pass_percentage',
            field=models.DecimalField(decimal_places=2, default=70.0, help_text='Passing cutoff percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='studentassessmentattempt',
            name='is_passed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
