# Generated by Django 6.0.3 on 2026-04-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_assessmenttemplate_pass_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentsection',
            name='section_time_minutes',
        ),
        migrations.RemoveField(
            model_name='assessmenttemplate',
            name='duration_minutes',
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'MCQ'), ('passage', 'Passage'), ('audio', 'Audio')], max_length=20),
        ),
    ]
