# Generated by Django 6.0.3 on 2026-04-17 05:05

from django.db import migrations


def fix_question_types(apps, schema_editor):
    AssessmentQuestion = apps.get_model("students", "AssessmentQuestion")

    # reading sections → passage
    AssessmentQuestion.objects.filter(
        section__skill="reading"
    ).exclude(question_type="passage").update(question_type="passage")

    # listening sections → audio
    AssessmentQuestion.objects.filter(
        section__skill="listening"
    ).exclude(question_type="audio").update(question_type="audio")


def reverse_fix_question_types(apps, schema_editor):
    # Cannot reliably reverse — no-op
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0024_remove_assessmentsection_section_time_minutes_and_more"),
    ]

    operations = [
        migrations.RunPython(fix_question_types, reverse_fix_question_types),
    ]
