# Generated by Django 6.0.3 on 2026-04-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_fix_reading_listening_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='student_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
