# Generated by Django 6.0.3 on 2026-04-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_studentprofile_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='student_profiles/'),
        ),
    ]
