# Generated by Django 6.0.3 on 2026-04-24 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0027_studentprofile_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlocation',
            name='student',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_location', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentlocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
