# Generated by Django 6.0.3 on 2026-04-25 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_alter_studentlocation_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedcourse',
            name='interest_type',
        ),
        migrations.RemoveField(
            model_name='recommendedcourse',
            name='resource_link',
        ),
        migrations.RemoveField(
            model_name='recommendedcourse',
            name='seat_limit',
        ),
    ]
