# Generated by Django 6.0.3 on 2026-05-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0031_studentnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentTemplateImporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gdoc_url', models.URLField(help_text="Paste the public Google Doc URL here. It must be shared as 'Anyone with the link can view'.", max_length=500)),
                ('status', models.TextField(blank=True, help_text='Status or errors of the import process.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Assessment Importer',
                'verbose_name_plural': 'Assessment Importers',
            },
        ),
    ]
