# Generated by Django 6.0.1 on 2026-05-16 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0032_assessmenttemplateimporter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendedcourse',
            options={'ordering': ['-created_at'], 'verbose_name': 'Promotional Banner', 'verbose_name_plural': 'Promotional Banners'},
        ),
    ]
