# Generated by Django 6.0.3 on 2026-05-23 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0033_alter_recommendedcourse_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedcourse',
            name='teachers',
        ),
    ]
