# Generated by Django 6.0.1 on 2026-06-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0035_courseenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
