# Generated by Django 6.0.1 on 2026-04-02 06:04

from django.db import migrations, models


def seed_app_languages(apps, schema_editor):
    AppLanguage = apps.get_model("accounts", "AppLanguage")
    languages = [
        {"name": "English", "code": "en"},
        {"name": "Azerbaijani", "code": "az"},
        {"name": "Russian", "code": "ru"},
    ]
    for language in languages:
        AppLanguage.objects.update_or_create(code=language["code"], defaults={"name": language["name"]})


def remove_seeded_app_languages(apps, schema_editor):
    AppLanguage = apps.get_model("accounts", "AppLanguage")
    AppLanguage.objects.filter(code__in=["en", "az", "ru"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Language of App',
                'verbose_name_plural': 'Languages of App',
                'db_table': 'language_of_app',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_app_languages, remove_seeded_app_languages),
    ]
