# Generated by Django 6.0.1 on 2026-04-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_applanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='purpose',
            field=models.CharField(choices=[('signup', 'Sign Up'), ('login', 'Sign In'), ('forgot_password', 'Forgot Password')], max_length=20),
        ),
    ]
