# Generated by Django 6.0.3 on 2026-04-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_onetimepassword_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
