# Generated by Django 6.0.3 on 2026-04-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_expo_push_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_first_assement_completed',
            field=models.BooleanField(default=False),
        ),
    ]
