# Generated by Django 6.0.3 on 2026-04-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_first_assement_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_push_notification',
            field=models.BooleanField(default=True),
        ),
    ]
