# Generated by Django 6.0.1 on 2026-04-04 03:33

from django.db import migrations, models


def seed_and_migrate_teacher_levels(apps, schema_editor):
    Teacher = apps.get_model("teachers", "Teacher")
    TeacherLevel = apps.get_model("teachers", "TeacherLevel")

    seeded_levels = {
        "beginner": TeacherLevel.objects.update_or_create(
            code="beginner",
            defaults={"name": "Beginner"},
        )[0],
        "intermediate": TeacherLevel.objects.update_or_create(
            code="intermediate",
            defaults={"name": "Intermediate"},
        )[0],
        "expert": TeacherLevel.objects.update_or_create(
            code="expert",
            defaults={"name": "Expert"},
        )[0],
    }

    for teacher in Teacher.objects.exclude(level=""):
        level = seeded_levels.get(teacher.level)
        if level:
            teacher.levels.add(level)


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=20, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='levels',
            field=models.ManyToManyField(related_name='teachers', to='teachers.teacherlevel'),
        ),
        migrations.RunPython(seed_and_migrate_teacher_levels, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='teacher',
            name='level',
        ),
    ]
