# Generated by Django 6.0.1 on 2026-04-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_remove_recommendedcourse_course_types_and_more'),
        ('teachers', '0002_teacherlevel_remove_teacher_level_teacher_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='recommended_courses',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='students.recommendedcourse'),
        ),
    ]
