# Generated by Django 6.0.1 on 2026-04-04 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_recommended_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='recommended_courses',
        ),
    ]
