# Generated by Django 6.0.1 on 2026-04-06 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_remove_teacher_recommended_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('number_of_students', models.PositiveIntegerField()),
                ('send_notification', models.TextField(blank=True, verbose_name='Send notification')),
                ('cancel', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_lists', to='teachers.teacher', verbose_name='Teacher name')),
            ],
            options={
                'verbose_name': 'Session List',
                'verbose_name_plural': 'Session List',
                'ordering': ['-date_time'],
            },
        ),
    ]
