# Generated by Django 6.0.1 on 2026-04-06 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_sessionlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdraw_type', models.CharField(max_length=255)),
                ('session_availability', models.CharField(max_length=255, verbose_name='Session availability')),
                ('accept', models.BooleanField(default=False)),
                ('cancel', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_requests', to='teachers.teacher', verbose_name='Teacher name')),
            ],
            options={
                'verbose_name': 'Pending Request',
                'verbose_name_plural': 'Pending Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
