# Generated by Django 6.0.1 on 2026-04-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_pendingrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_link', models.URLField(blank=True)),
                ('youtube_link', models.URLField(blank=True)),
                ('adult_learning_club_link', models.URLField(blank=True)),
                ('kids_learning_club_link', models.URLField(blank=True)),
                ('file_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('file_upload', models.FileField(upload_to='general_info_files/')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Delete')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'General Info',
                'verbose_name_plural': 'General Info',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
