# Generated by Django 6.0.1 on 2026-04-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_generalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinfo',
            name='whatsapp_link',
            field=models.URLField(blank=True),
        ),
    ]
