# Generated by Django 6.0.1 on 2026-04-07 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_generalinfo_whatsapp_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='levels',
            new_name='capability_level',
        ),
    ]
