# Generated by Django 6.0.1 on 2026-04-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_remove_teacher_levels_teacher_capability_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinfo',
            name='library_link',
            field=models.URLField(blank=True),
        ),
    ]
