# Generated by Django 6.0.3 on 2026-04-18 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0011_teacherprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachersLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='teachers.teacherprofile', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Teachers Location',
                'verbose_name_plural': 'Teachers Locations',
            },
        ),
    ]
