# Generated by Django 6.0.3 on 2026-04-18 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0013_teacheravailability_teacherslot_studentbooking'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacheravailability',
            unique_together={('teacher', 'day_of_week', 'start_time')},
        ),
    ]
