# Generated by Django 6.0.3 on 2026-04-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0014_alter_teacheravailability_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionlist',
            name='meeting_link',
            field=models.URLField(blank=True, null=True, verbose_name='Meeting Link'),
        ),
    ]
