# Generated by Django 6.0.3 on 2026-04-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0015_sessionlist_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherslot',
            name='meeting_link',
            field=models.URLField(blank=True, null=True, verbose_name='Meeting Link'),
        ),
    ]
