# Generated by Django 6.0.3 on 2026-04-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0016_teacherslot_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbooking',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentbooking',
            name='marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
