# Generated by Django 6.0.3 on 2026-04-20 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0017_studentbooking_feedback_studentbooking_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingrequest',
            name='accept',
        ),
        migrations.RemoveField(
            model_name='pendingrequest',
            name='cancel',
        ),
        migrations.RemoveField(
            model_name='pendingrequest',
            name='session_availability',
        ),
        migrations.RemoveField(
            model_name='pendingrequest',
            name='teacher_name',
        ),
        migrations.RemoveField(
            model_name='pendingrequest',
            name='withdraw_type',
        ),
        migrations.AddField(
            model_name='pendingrequest',
            name='details',
            field=models.CharField(default='', help_text='e.g. Monday 09:00 AM', max_length=255),
        ),
        migrations.AddField(
            model_name='pendingrequest',
            name='request_type',
            field=models.CharField(choices=[('session_cancellation', 'Session Cancellation'), ('availability_withdrawal', 'Availability Withdrawal')], default='session_cancellation', max_length=50),
        ),
        migrations.AddField(
            model_name='pendingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='pendingrequest',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_requests', to='teachers.teacherprofile'),
        ),
    ]
