# Generated by Django 6.0.3 on 2026-04-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0018_remove_pendingrequest_accept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='whatsapp_link',
            field=models.URLField(blank=True, help_text="WhatsApp group link for teacher's room", null=True),
        ),
        migrations.AddField(
            model_name='teacherslot',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to='curriculums/'),
        ),
        migrations.AddField(
            model_name='teacherslot',
            name='title',
            field=models.CharField(default='General Class', max_length=255),
        ),
    ]
