# Generated by Django 6.0.3 on 2026-04-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0019_teacherprofile_whatsapp_link_teacherslot_curriculum_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherslot',
            old_name='curriculum',
            new_name='teachers_curriculum',
        ),
        migrations.RemoveField(
            model_name='sessionlist',
            name='meeting_link',
        ),
        migrations.RemoveField(
            model_name='teacherslot',
            name='meeting_link',
        ),
        migrations.AddField(
            model_name='sessionlist',
            name='whatsapp_room_link',
            field=models.URLField(blank=True, null=True, verbose_name='WhatsApp Room Link'),
        ),
        migrations.AddField(
            model_name='teacherslot',
            name='whatsapp_room_link',
            field=models.URLField(blank=True, null=True, verbose_name='WhatsApp Room Link'),
        ),
    ]
