# Generated by Django 6.0.3 on 2026-04-22 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0020_rename_curriculum_teacherslot_teachers_curriculum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingrequest',
            name='availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_requests', to='teachers.teacheravailability'),
        ),
        migrations.AddField(
            model_name='pendingrequest',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellation_requests', to='teachers.teacherslot'),
        ),
    ]
