# Generated by Django 6.0.3 on 2026-04-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0021_pendingrequest_availability_pendingrequest_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherslocation',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='teacherslocation',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
    ]
