# Generated by Django 6.0.3 on 2026-04-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0022_alter_teacherslocation_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalinfo',
            old_name='file_upload',
            new_name='calender_upload',
        ),
        migrations.RemoveField(
            model_name='generalinfo',
            name='file_name',
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='calender_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
