# Generated by Django 6.0.3 on 2026-04-25 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0023_rename_file_upload_generalinfo_calender_upload_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalinfo',
            old_name='calender_name',
            new_name='calender_type',
        ),
    ]
