# Generated by Django 6.0.3 on 2026-05-04 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0024_rename_calender_name_generalinfo_calender_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='whatsapp_link',
            new_name='teachers_room',
        ),
    ]
