# Generated by Django 6.0.3 on 2026-05-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0025_rename_whatsapp_link_teacherprofile_teachers_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionlist',
            old_name='whatsapp_room_link',
            new_name='meeting_link',
        ),
        migrations.AlterField(
            model_name='sessionlist',
            name='meeting_link',
            field=models.URLField(blank=True, null=True, verbose_name='Meeting Link'),
        ),
        migrations.RenameField(
            model_name='teacherslot',
            old_name='whatsapp_room_link',
            new_name='meeting_link',
        ),
        migrations.AlterField(
            model_name='teacherslot',
            name='meeting_link',
            field=models.URLField(blank=True, null=True, verbose_name='Meeting Link'),
        ),
    ]
