# Generated by Django 6.0.3 on 2026-05-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0026_remove_sessionlist_whatsapp_room_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingrequest',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Cancellation Reason'),
        ),
    ]
