# Generated by Django 6.0.3 on 2026-05-23 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0034_remove_recommendedcourse_teachers'),
        ('teachers', '0027_pendingrequest_cancellation_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='students.recommendedcourse', verbose_name='Promotional Banner')),
                ('teachers', models.ManyToManyField(blank=True, related_name='course_modules', to='teachers.teacher', verbose_name='Choose your teacher list')),
            ],
            options={
                'verbose_name': 'Course Module',
                'verbose_name_plural': 'Course Modules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseModuleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('course_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='teachers.coursemodule')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_sessions', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Session with teacher available date',
                'verbose_name_plural': 'Sessions with teacher available date',
                'ordering': ['course_module', 'teacher', 'date'],
            },
        ),
    ]
