# Generated by Django 6.0.3 on 2026-05-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0028_coursemodule_coursemodulesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodulesession',
            name='session_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Session Name'),
        ),
        migrations.AlterField(
            model_name='coursemodulesession',
            name='date',
            field=models.DateField(verbose_name='Available Date'),
        ),
    ]
