# Generated by Django 6.0.3 on 2026-05-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0029_coursemodulesession_session_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemodulesession',
            options={'ordering': ['course_module', 'teacher', 'date'], 'verbose_name': 'Session', 'verbose_name_plural': 'Module Sessions'},
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Module Name'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='course_modules', to='teachers.teacher', verbose_name='Teachers'),
        ),
    ]
