# Generated by Django 6.0.3 on 2026-05-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0030_alter_coursemodulesession_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodule',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Module Name'),
        ),
    ]
