# Generated by Django 6.0.3 on 2026-05-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0031_alter_coursemodule_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemodulesession',
            options={'ordering': ['course_module', 'teacher', 'available_start_date'], 'verbose_name': 'Session', 'verbose_name_plural': 'Module Sessions'},
        ),
        migrations.RemoveField(
            model_name='coursemodulesession',
            name='date',
        ),
        migrations.AddField(
            model_name='coursemodulesession',
            name='available_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Available End Date'),
        ),
        migrations.AddField(
            model_name='coursemodulesession',
            name='available_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Available Start Date'),
        ),
    ]
