# Generated by Django 6.0.1 on 2026-05-23 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0032_alter_coursemodulesession_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemodulesession',
            options={'ordering': ['id'], 'verbose_name': 'Session', 'verbose_name_plural': 'Module Sessions'},
        ),
        migrations.RemoveField(
            model_name='coursemodule',
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='coursemodulesession',
            name='available_end_date',
        ),
        migrations.RemoveField(
            model_name='coursemodulesession',
            name='available_start_date',
        ),
        migrations.RemoveField(
            model_name='coursemodulesession',
            name='teacher',
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='available_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Available End Date'),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='available_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Available Start Date'),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_modules', to='teachers.teacher', verbose_name='Teacher'),
        ),
    ]
