# Generated by Django 6.0.1 on 2026-05-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0033_alter_coursemodulesession_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodule',
            name='available_end_date',
        ),
        migrations.RemoveField(
            model_name='coursemodule',
            name='available_start_date',
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='availability_date_range',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Availability Date Range'),
        ),
    ]
