# Generated by Django 6.0.1 on 2026-05-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0034_remove_coursemodule_available_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodule',
            name='availability_date_range',
        ),
        migrations.AddField(
            model_name='coursemodulesession',
            name='availability_date_range',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Availability Date Range'),
        ),
    ]
