# Generated by Django 6.0.1 on 2026-06-02 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0035_remove_coursemodule_availability_date_range_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursemodulesession',
            unique_together={('course_module', 'availability_date_range')},
        ),
    ]
