# Generated by Django 6.0.1 on 2026-06-29 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0036_alter_coursemodulesession_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbooking',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='teachers.coursemodulesession'),
        ),
    ]
