# Generated by Django 6.0.1 on 2026-06-29 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0035_courseenrollment'),
        ('teachers', '0037_studentbooking_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbooking',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_bookings', to='students.recommendedcourse'),
        ),
    ]
