# Generated by Django 6.0.1 on 2026-07-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0038_studentbooking_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodulesession',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coursemodulesession',
            name='offline_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
